name: mf6xtd

channels:
  - conda-forge

dependencies:
  # required 
  - python<=3.11
  - numpy>=1.15.0
  - matplotlib>=1.4.0
  - jupyterlab

  # development
  - pkg-config
  - openmpi
  - gfortran
  - petsc
  - meson>=1.1.0
  - ninja

  # flopy
  - python-dateutil>=2.4.0
  - affine
  - scipy
  - pandas
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely>=1.8
  - geos
  - geojson
  - vtk
  - rasterstats
  - pyvista
  - imageio
  - pymetis
  - netcdf4
  - xarray
  - flopy
  - xmipy
  - modflowapi
